var PUBLISH_ROOT = '/Metalhead.jl/0.7.1';
var PUBLISH_VERSION = "0.7.1";
var PUBLISH_VERSIONS = [
    ["v0.7.3","/Metalhead.jl/v0.7.3/index.html"],
    ["v0.7.2","/Metalhead.jl/v0.7.2/index.html"],
    ["v0.7.1","/Metalhead.jl/v0.7.1/index.html"],
    ["v0.7.0","/Metalhead.jl/v0.7.0/index.html"],
    ["v0.7","/Metalhead.jl/v0.7/index.html"],
    ["v0.6.1","/Metalhead.jl/v0.6.1/index.html"],
    ["v0.6.0","/Metalhead.jl/v0.6.0/index.html"],
    ["v0.6","/Metalhead.jl/v0.6/index.html"],
    ["stable","/Metalhead.jl/stable/index.html"],
    ["previews","/Metalhead.jl/previews/index.html"],
    ["dev","/Metalhead.jl/dev/index.html"],
    ["0.8.0-DEV","/Metalhead.jl/0.8.0-DEV/index.html"],
    ["0.7.4","/Metalhead.jl/0.7.4/index.html"],
    ["0.7.3-DEV","/Metalhead.jl/0.7.3-DEV/index.html"],
    ["0.7.3","/Metalhead.jl/0.7.3/index.html"],
    ["0.7.2-DEV","/Metalhead.jl/0.7.2-DEV/index.html"],
    ["0.7.2","/Metalhead.jl/0.7.2/index.html"],
    ["0.7.1","/Metalhead.jl/0.7.1/index.html"],
    ["0.7.0","/Metalhead.jl/0.7.0/index.html"],
    ["0.6.1","/Metalhead.jl/0.6.1/index.html"],
    ["0.6.0","/Metalhead.jl/0.6.0/index.html"],
];
