name: PublishStable

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish Documentation (stable)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        run: |
          cd gh-pages
          julia --color=yes --project=../docs -e "using Pkg; Pkg.instantiate()"
          julia --color=yes --project=../docs -e 'include("../docs/make.jl"); build_and_deploy("stable")'
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "(stable) Built by Publish.jl."
          git push
